#!/bin/sh
# Setup a machine for Sublime Text 2
# set -x

# symlink settings in
sublime_dir=~/.config/sublime-text-2/Packages/
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -s "$DOTFILES/sublime2/User" "$sublime_dir"
ln -s "$DOTFILES/sublime2/subl_handler.sh" "$HOME/bin/"

# Grab the Soda theme
# cd "$sublime_dir"
# git clone https://github.com/buymeasoda/soda-theme/ "Theme - Soda"
